name: IBA-taxonomy
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - snakemake=8.2.1
  - biopython
  - pandas
  - gappa
  - epa-ng
  - raxml-ng
  - vsearch
  - tqdm
  - pip
  - pip:
    - snakemake-executor-plugin-slurm==0.3.0
