name: IBA-taxonomy
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.10
  - snakemake=8*
  - biopython
  - pandas
  - gappa
  - epa-ng
  - raxml-ng
  - vsearch
  - tqdm
  - pip
  - pip:
    - snakemake-executor-plugin-slurm
