use-conda: True
use-envmodules: True
use-apptainer: True
keep-going: True
printshellcmds: True
rerun-triggers: mtime
local-cores: 1
jobs: 100
default-resources: "slurm_account=naiss2023-5-209"
latency-wait: 5
executor: slurm
rerun-incomplete: True