use-conda: True
use-envmodules: True
use-apptainer: True
keep-going: True
printshellcmds: True
rerun-triggers: mtime
local-cores: 1
jobs: 100
latency-wait: 5
executor: slurm
rerun-incomplete: True

default-resources: 
  slurm_account: "<your-slurm-account"

#set-resources:
#  epa_ng:
#    contstraint: "mem256GB"