use-conda: True
use-envmodules: True
use-apptainer: True
keep-going: True
printshellcmds: True
rerun-triggers: mtime
local-cores: 1
jobs: 100
latency-wait: 5
executor: slurm
rerun-incomplete: True

default-resources: 
  slurm_account: "<your-slurm-account>"
  #slurm_partition: "core"

set-resources:
  epa_ng:
    runtime: 10080
  qiime2_classify_vsearch:
    runtime: 10080
    #slurm_partition: "node"

set-threads:
  qiime2_classify_vsearch: 20
