benchmark:
  coidb.221216.7lvl:
    #fasta: "data/benchmark/bold_clustered.sintax.7levels.fasta"
    fasta: "benchmark/coidb.221216.7lvl/subseqs.fasta"
    taxonomy: "data/benchmark/coidb.221216.taxonomy.tsv.gz"
    ranks: ["kingdom","phylum","class","order","family","genus","species"]
    # should the reference sequences be trimmed to the region of interest?
    extract_subseq: False
    subseq_min_len: 300 # Minimum length of subsequence to be extracted from the reference
    hmm_from: 78
    hmm_to: 202
    asv_seq: "AATAAATAACATAAGATTTTGATTATTACCCCCTTCTTTATCTTTACTATTAATTAGAAGAATAGTTGAAACTGGAACAGGTACCGGATGAACTGTTTACCCACCATTATCTTCTATTATTGCTCATACAGGATCATCAGTAGATTTTTCAATTTTTTCTTTACATATTGCAGGAATTTCATCTATTTTAGGAGCTATTAATTTTATTTCAACTATATTAAATATAAAAATCAAATTTTTAAAATTTGATCAAATTTCATTATTTATTTGATCAATTTTAATTACAACTGTATTATTACTTTTATCATTACCTGTATTAGCAGGAGCAATTACTATACTATTAACAGATCGAAATTTAAATACATCATTTTTTGATCCTATAGGAGGAGGAGATCCAATTCTTTATCAACATTTATTT"
    
benchmark_phylo:
  coidb.221216.7lvl:
    #fasta: "data/benchmark/bold_clustered.sintax.7levels.fasta"
    fasta: "benchmark/coidb.221216.7lvl/subseqs.fasta"
    taxonomy: "data/benchmark/coidb.221216.taxonomy.tsv.gz"
    tree_fasta: "data/chesters_2017/hmmersearch_OUT_ch2017_noduplic_trimmed.fas"
    tree_taxonomy: "data/chesters_2017/taxonomy.tsv"
    ranks: ["kingdom","phylum","class","order","family","genus","species"]

tools:
  - metabuli
  - kaiju
  - sintax
  #- epa-ng 

metabuli:
  ref:
    coi.test: "data/coi.subsample.fasta"
  query:
    coi.test_query: "data/coi.subsample.fasta"
  runs:
    default:
      options: ""
    illumina:
      options: "--min-score 0.15 --min-sp-score 0.5"
    #pacbio_hifi: 
    #  options: "--min-score 0.07 --min-sp-score 0.3"
    #pacbio_sequel:
    #  options: "--min-score 0.005"
    #ont:
    #  options: "--min-score 0.008"

sintax:
  ref:
    coidb.221216.7lvl.case1:
      fasta: "benchmark/coidb.221216.7lvl/case1-keep-species-in-db/train.fasta"
      ranks: ["kingdom","phylum","class","order","family","genus","species"]
    coidb.221216.7lvl.case2: 
      fasta: "benchmark/coidb.221216.7lvl/case2-keep-species-remove-identical/train.fasta"
      ranks: ["kingdom","phylum","class","order","family","genus","species"]
    coidb.221216.7lvl.case3: 
      fasta: "benchmark/coidb.221216.7lvl/case3-remove-species-keep-genus/train.fasta"
      ranks: ["kingdom","phylum","class","order","family","genus","species"]
    coidb.221216.7lvl.case4: 
      fasta: "benchmark/coidb.221216.7lvl/case4-remove-genus-keep-family/train.fasta"
      ranks: ["kingdom","phylum","class","order","family","genus","species"]
    coidb.221216.7lvl.case5: 
      fasta: "benchmark/coidb.221216.7lvl/case5-remove-family/train.fasta"
      ranks: ["kingdom","phylum","class","order","family","genus","species"]
  query:
    coidb.221216.7lvl.case1: "benchmark/coidb.221216.7lvl/case1-keep-species-in-db/test.fasta"
    coidb.221216.7lvl.case2: "benchmark/coidb.221216.7lvl/case2-keep-species-remove-identical/test.fasta"
    coidb.221216.7lvl.case3: "benchmark/coidb.221216.7lvl/case3-remove-species-keep-genus/test.fasta"
    coidb.221216.7lvl.case4: "benchmark/coidb.221216.7lvl/case4-remove-genus-keep-family/test.fasta"
    coidb.221216.7lvl.case5: "benchmark/coidb.221216.7lvl/case5-remove-family/test.fasta"
  randseed: 15
  cutoff: 0.8

dada2:
  ref:
    coidb.221216.7lvl.case1:
      fasta: "benchmark/coidb.221216.7lvl/case1-keep-species-in-db/train.fasta"
      ranks: ["kingdom","phylum","class","order","family","genus"]
      format: "sintax"
    coidb.221216.7lvl.case2: 
      fasta: "benchmark/coidb.221216.7lvl/case2-keep-species-remove-identical/train.fasta"
      ranks: ["kingdom","phylum","class","order","family","genus"]
      format: "sintax"
    coidb.221216.7lvl.case3: 
      fasta: "benchmark/coidb.221216.7lvl/case3-remove-species-keep-genus/train.fasta"
      ranks: ["kingdom","phylum","class","order","family","genus"]
      format: "sintax"
    coidb.221216.7lvl.case4: 
      fasta: "benchmark/coidb.221216.7lvl/case4-remove-genus-keep-family/train.fasta"
      ranks: ["kingdom","phylum","class","order","family","genus"]
      format: "sintax"
    coidb.221216.7lvl.case5: 
      fasta: "benchmark/coidb.221216.7lvl/case5-remove-family/train.fasta"
      ranks: ["kingdom","phylum","class","order","family","genus"]
      format: "sintax"
  query:
    coidb.221216.7lvl.case1: "benchmark/coidb.221216.7lvl/case1-keep-species-in-db/test.fasta"
    coidb.221216.7lvl.case2: "benchmark/coidb.221216.7lvl/case2-keep-species-remove-identical/test.fasta"
    coidb.221216.7lvl.case3: "benchmark/coidb.221216.7lvl/case3-remove-species-keep-genus/test.fasta"
    coidb.221216.7lvl.case4: "benchmark/coidb.221216.7lvl/case4-remove-genus-keep-family/test.fasta"
    coidb.221216.7lvl.case5: "benchmark/coidb.221216.7lvl/case5-remove-family/test.fasta"
  minBoot: 80

qiime2:
  ref:
    coidb.221216.7lvl.case1:
      fasta: "benchmark/coidb.221216.7lvl/case1-keep-species-in-db/train.fasta"
      taxonomy: "benchmark/coidb.221216.7lvl/case1-keep-species-in-db/train.tsv"
      ranks: ["kingdom","phylum","class","order","family","genus","species"]
      format: "sintax"
    coidb.221216.7lvl.case2: 
      fasta: "benchmark/coidb.221216.7lvl/case2-keep-species-remove-identical/train.fasta"
      taxonomy: "benchmark/coidb.221216.7lvl/case2-keep-species-remove-identical/train.tsv"
      ranks: ["kingdom","phylum","class","order","family","genus","species"]
      format: "sintax"
    coidb.221216.7lvl.case3: 
      fasta: "benchmark/coidb.221216.7lvl/case3-remove-species-keep-genus/train.fasta"
      taxonomy: "benchmark/coidb.221216.7lvl/case3-remove-species-keep-genus/train.tsv"
      ranks: ["kingdom","phylum","class","order","family","genus","species"]
      format: "sintax"
    coidb.221216.7lvl.case4: 
      fasta: "benchmark/coidb.221216.7lvl/case4-remove-genus-keep-family/train.fasta"
      taxonomy: "benchmark/coidb.221216.7lvl/case4-remove-genus-keep-family/train.tsv"
      ranks: ["kingdom","phylum","class","order","family","genus","species"]
      format: "sintax"
    coidb.221216.7lvl.case5: 
      fasta: "benchmark/coidb.221216.7lvl/case5-remove-family/train.fasta"
      taxonomy: "benchmark/coidb.221216.7lvl/case5-remove-family/train.tsv"
      ranks: ["kingdom","phylum","class","order","family","genus","species"]
      format: "sintax"
  query:
    coidb.221216.7lvl.case1: "benchmark/coidb.221216.7lvl/case1-keep-species-in-db/test.fasta"
    coidb.221216.7lvl.case2: "benchmark/coidb.221216.7lvl/case2-keep-species-remove-identical/test.fasta"
    coidb.221216.7lvl.case3: "benchmark/coidb.221216.7lvl/case3-remove-species-keep-genus/test.fasta"
    coidb.221216.7lvl.case4: "benchmark/coidb.221216.7lvl/case4-remove-genus-keep-family/test.fasta"
    coidb.221216.7lvl.case5: "benchmark/coidb.221216.7lvl/case5-remove-family/test.fasta"


kaiju:
  ref:
    coi.test: "data/coi.subsample.fasta"
  query:
    coi.test_query: "data/coi.subsample.fasta"
  settings: ""
    
epa-ng:
  # preplacement heuristics to test
  # dyn-heur: default, this is the accumulated threshold method where branches are added to the set 
  # of candidates until the sum of their LWR exceed a user specified threshold. The default setting is 
  # 0.99999, corresponding to a covered likelihood weight of 99.999%.
  # baseball-heur: works identically to the baseball heuristic from pplacer, with default settings 
  # (--strike-box 3.0, --max-strikes 6, --max-pitches 40)
  # no-heur: disables preplacement heuristics
  heuristics:
    - "dyn-heur"
    - "baseball-heur"
    - "no-heur"
  # Set input options
  ref:
    chester_2017:
      tree: "data/chesters_2017/chesters_2017_trimmed_tree.nwk"
      tree_format: "newick"
      msa: "data/chesters_2017/hmmersearch_OUT_ch2017_noduplic_trimmed.fas"
      msa_format: "fasta"
      ref_taxonomy: "data/chesters_2017/taxonomy.tsv"
      tree_ranks:
        - "superkingdom"
        - "phylum"
        - "class"
        - "order"
        - "family"
        - "genus"
        - "species"
      model: "GTR+G+F"
  query: 
    coidb.221216.7lvl.case1: "benchmark_phylo/coidb.221216.7lvl/case1-sample_keep_species_remove_identical_phylo/test.fasta"
    coidb.221216.7lvl.case2: "benchmark_phylo/coidb.221216.7lvl/case2-sample_keep_genus_remove_species_phylo/test.fasta"
    coidb.221216.7lvl.case3: "benchmark_phylo/coidb.221216.7lvl/case3-sample_keep_family_remove_genus_phylo/test.fasta"
    coidb.221216.7lvl.case4: "benchmark_phylo/coidb.221216.7lvl/case4-sample_keep_order_remove_family_phylo/test.fasta"
  gappa:
    # Ratio by which LWR is split between annotations if an edge has two possible
    # annotations. Specifies the amount going to the proximal annotation. If not
    # set program will determine the ratio automatically from the 'distal length'
    # specified per placement.
    distribution_ratio: -1
    # For assignment of taxonomic labels to the reference tree, require this
    # consensus threshold. Example: if set to 0.6, and 60% of an inner node's
    # descendants share a taxonomic path, set that path at the inner node.
    consensus_thresh: 1
    
plusplacer-taxtastic:
# Set input options
  ref:
    chester_2017:
      tree: "data/chesters_2017/chesters_2017_trimmed_tree.nwk"
      tree_format: "newick"
      msa: "data/chesters_2017/hmmersearch_OUT_ch2017_noduplic_trimmed.fas"
      msa_format: "fasta"
      ref_taxonomy: "data/chesters_2017/taxonomy.tsv"
      tree_ranks:
        - "superkingdom"
        - "phylum"
        - "class"
        - "order"
        - "family"
        - "genus"
        - "species"
      model: "GTR+G+F"
  query: 
    coidb.221216.7lvl.case1: "benchmark_phylo/coidb.221216.7lvl/case1-sample_keep_species_remove_identical_phylo/test.fasta"
    coidb.221216.7lvl.case2: "benchmark_phylo/coidb.221216.7lvl/case2-sample_keep_genus_remove_species_phylo/test.fasta"
    coidb.221216.7lvl.case3: "benchmark_phylo/coidb.221216.7lvl/case3-sample_keep_family_remove_genus_phylo/test.fasta"
    coidb.221216.7lvl.case4: "benchmark_phylo/coidb.221216.7lvl/case4-sample_keep_order_remove_family_phylo/test.fasta"