tools:
  - sintax
  - epa-ng 
  #- metabuli
  #- kaiju
  #- dada2
  #- qiime2_sklearn
  #- qiime2_vsearch

dada2:
  ref:
    test: 
      fasta: ""
      fmt: "dada2"
      ranks: ["kingdom","phylum","class","order","family","genus","species"]
  query:
    test: "data/test/test.fasta"

qiime2:
  ref:
    test:
      fasta: ""
      taxonomy: ""
      fmt: ""
      ranks: ["kingdom","phylum","class","order","family","genus","species"]
  query:
    test: "data/test/test.fasta"


metabuli:
  ref:
    test: ""
  query: 
    test: "data/test/test.fasta"
  runs:
    default:
      options: ""
    illumina:
      options: "--min-score 0.15 --min-sp-score 0.5"
    pacbio_hifi: 
      options: "--min-score 0.07 --min-sp-score 0.3"
    pacbio_sequel:
      options: "--min-score 0.005"
    ont:
      options: "--min-score 0.008"

sintax:
  ref:
    test: 
      fasta: ""
      ranks: ["kingdom","phylum","class","order","family","genus","species"]
  query:
    test: "data/test/test.fasta"
  randseed: 15
  cutoff: 0.8  

kaiju:
  ref:
    test: ""
  query:
    test: "data/test/test.fasta"
  settings: ""
    
phylogeny:
  # Set input options
  ref:
    chester_2017:
      tree: "data/chesters_2017/chesters_2017_trimmed_tree.nwk"
      tree_format: "newick"
      msa: "data/chesters_2017/hmmersearch_OUT_ch2017_noduplic_trimmed.refmt.fas"
      msa_format: "fasta"
      tree_ranks:
        - "Kingdom"
        - "Phylum"
        - "Class"
        - "Order"
        - "Family"
        - "Genus"
        - "Species"
      ref_taxonomy: "data/chesters_2017/taxonomy.tsv"
      model: "GTR+G+F"
      # Use this reference to reassign sintax queries that are
      # assigned to 'rank' below (Class by default) with taxlabel 
      # 'taxa' (Insecta) by default. This means that sequences
      # with Class == Insecta but unclassified at rank 'Order'
      # will be extracted and reassigned with EPA-NG
      reassign_sintax:
        rank: "Class"
        taxa: "Insecta"
        update_ranks: ["Order"]
        downstream_ranks: ["Family","Genus","Species","BOLD_bin"]
  query: 
    test: "data/test/test.fasta"
  epa-ng:
    # preplacement heuristics to test
    # dyn-heur: default, this is the accumulated threshold method where branches are added to the set 
    # of candidates until the sum of their LWR exceed a user specified threshold. The default setting is 
    # 0.99999, corresponding to a covered likelihood weight of 99.999%.
    # baseball-heur: works identically to the baseball heuristic from pplacer, with default settings 
    # (--strike-box 3.0, --max-strikes 6, --max-pitches 40)
    # no-heur: disables preplacement heuristics
    heuristics:
      #- "dyn-heur"
      - "baseball-heur"
      #- "no-heur"
  gappa:
    # Ratio by which LWR is split between annotations if an edge has two possible
    # annotations. Specifies the amount going to the proximal annotation. If not
    # set program will determine the ratio automatically from the 'distal length'
    # specified per placement.
    distribution_ratio: -1
    # For assignment of taxonomic labels to the reference tree, require this
    # consensus threshold. Example: if set to 0.6, and 60% of an inner node's
    # descendants share a taxonomic path, set that path at the inner node.
    consensus_thresh: 1